// src/adapters/CinemaCarousel.jsx
/**
 * CinemaCarousel — React 适配组件（无构建依赖，复制进任意 React 16.8+ 项目即可）
 *
 * 项目内使用（推荐）：
 *   import { createCarousel } from 'cinema-carousel/src/cinema-carousel.core.js';
 *   （把下面 `const { createCarousel } = window.CinemaCarouselCore;` 换成这行 import）
 *
 * Props:
 *   items        必填，[{ src, alt, title, desc, href?, eyebrow? }]
 *   initialIndex 初始展开卡片，默认 0
 *   autoplay     自动轮播间隔 ms，0 = 关闭
 *   loop         是否循环，默认 false
 *   showControls 是否渲染底部控制条，默认 true
 *   onChange     (index) => void，展开卡片变化时触发
 */
const { createCarousel } = window.CinemaCarouselCore;

function CinemaCarousel({
  items,
  initialIndex = 0,
  autoplay = 0,
  loop = false,
  showControls = true,
  onChange,
}) {
  const coreRef = React.useRef(null);
  if (!coreRef.current) {
    // 惰性初始化：首次渲染即创建状态机，保证 render 时快照可用
    coreRef.current = createCarousel({ count: items.length, initialIndex, autoplay, loop });
  }
  const core = coreRef.current;
  const [snap, setSnap] = React.useState(core.getState());
  const onChangeRef = React.useRef(onChange);
  onChangeRef.current = onChange;

  React.useEffect(() => {
    const unsub = core.subscribe((s) => {
      setSnap(s);
      onChangeRef.current && onChangeRef.current(s.index);
    });
    if (autoplay > 0) core.startAutoplay();
    return () => { unsub(); core.destroy(); };
    // items.length 变化属于重建场景，其余 props 变化不重建
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [items.length]);

  const state = snap;

  const onKeyDown = (e) => {
    if (e.key === 'ArrowLeft') core.prev({ user: true });
    if (e.key === 'ArrowRight') core.next({ user: true });
  };

  const pad2 = (n) => String(n).padStart(2, '0');

  return (
    <div className="cc-stage" tabIndex={0} onKeyDown={onKeyDown}>
      <div className="cc-carousel">
        {items.map((item, i) => (
          <article
            key={i}
            className={
              'cc-card' +
              (i === state.index ? ' is-active' : '') +
              (state.collapsed[i] ? ' is-collapsed' : '')
            }
            onClick={() => core.goTo(i, { user: true })}
          >
            <img className="cc-card__img" src={item.src} alt={item.alt || ''} draggable={false} />
            <div className="cc-card__scrim" />
            <header className="cc-card__head">
              <span className="cc-card__num">{pad2(i + 1)}</span>
              <span className="cc-card__num cc-card__num--end">{pad2(i + 1)}</span>
            </header>
            <p className="cc-card__eyebrow">
              <span className="cc-dot" />
              {item.eyebrow || 'VISUAL IDENTITY'}
            </p>
            <h2 className="cc-card__title">{item.title}</h2>
            <div className="cc-card__body">
              <div className="cc-card__info">
                <span className="cc-card__index">{pad2(i + 1)}</span>
                <h3 className="cc-card__heading">{item.title}</h3>
                <p className="cc-card__desc">
                  {(item.desc || '').split('\n').map((line, k, arr) => (
                    <React.Fragment key={k}>
                      {line}
                      {k < arr.length - 1 && <br />}
                    </React.Fragment>
                  ))}
                </p>
                {item.href && (
                  <a className="cc-card__cta" href={item.href} onClick={(e) => e.stopPropagation()}>
                    View project
                    <span className="cc-card__cta-arrow">
                      <svg viewBox="0 0 16 16" fill="none">
                        <path d="M3 8h9M8.5 4.5 12 8l-3.5 3.5" stroke="#111" strokeWidth="1.5"
                          strokeLinecap="round" strokeLinejoin="round" />
                      </svg>
                    </span>
                  </a>
                )}
              </div>
            </div>
          </article>
        ))}
      </div>

      {showControls && (
        <footer className="cc-controls">
          <div className="cc-controls__counter">
            <span className="cc-counter-current">{pad2(state.index + 1)}</span>{' '}
            <span className="cc-controls__total">/ {pad2(items.length)}</span>
          </div>
          <div
            className="cc-controls__progress"
            onClick={(e) => {
              const rect = e.currentTarget.getBoundingClientRect();
              const ratio = (e.clientX - rect.left) / rect.width;
              core.goTo(Math.round(ratio * (items.length - 1)), { user: true });
            }}
          >
            <div
              className="cc-controls__bar"
              style={{
                width: `${100 / items.length}%`,
                left: `${(100 / items.length) * state.index}%`,
              }}
            />
          </div>
          <div className="cc-controls__nav">
            <button
              className="cc-nav-btn cc-prev"
              aria-label="上一张"
              disabled={state.index === 0 && !loop}
              onClick={() => core.prev({ user: true })}
            >
              <svg viewBox="0 0 20 20" fill="none">
                <path d="M11.5 5.5 7 10l4.5 4.5" stroke="currentColor" strokeWidth="1.5"
                  strokeLinecap="round" strokeLinejoin="round" />
              </svg>
            </button>
            <button
              className="cc-nav-btn cc-next"
              aria-label="下一张"
              disabled={state.index === items.length - 1 && !loop}
              onClick={() => core.next({ user: true })}
            >
              <svg viewBox="0 0 20 20" fill="none">
                <path d="M8.5 5.5 13 10l-4.5 4.5" stroke="currentColor" strokeWidth="1.5"
                  strokeLinecap="round" strokeLinejoin="round" />
              </svg>
            </button>
          </div>
        </footer>
      )}
    </div>
  );
}

// 打包器场景：取消下面这行注释（或改为 export default CinemaCarousel）
// export default CinemaCarousel;

// src/adapters/CinemaCarousel.vue
<!--
  CinemaCarousel — Vue 3 适配组件（<script setup>，复制进任意 Vue 3 项目即可）

  项目内使用（推荐）：
    import { createCarousel } from 'cinema-carousel/src/cinema-carousel.core.js';
    （把下面 `const { createCarousel } = window.CinemaCarouselCore;` 换成这行 import）

  用法：
    <CinemaCarousel :items="items" :initial-index="0" :autoplay="4500" @change="i => ..." />
-->
<script setup>
import { ref, onMounted, onBeforeUnmount } from 'vue';

const { createCarousel } = window.CinemaCarousel;

const props = defineProps({
  items: { type: Array, required: true },        // [{ src, alt, title, desc, href?, eyebrow? }]
  initialIndex: { type: Number, default: 0 },
  autoplay: { type: Number, default: 0 },        // ms，0 = 关闭
  loop: { type: Boolean, default: false },
  showControls: { type: Boolean, default: true },
});

const emit = defineEmits(['change']);

const pad2 = (n) => String(n).padStart(2, '0');
const index = ref(props.initialIndex);
let core = null;
let unsub = null;

function cardCls(i) {
  return [
    'cc-card',
    { 'is-active': i === index.value },
    { 'is-collapsed': i !== index.value },
  ];
}

function onProgressClick(e) {
  const rect = e.currentTarget.getBoundingClientRect();
  const ratio = (e.clientX - rect.left) / rect.width;
  core?.goTo(Math.round(ratio * (props.items.length - 1)), { user: true });
}

onMounted(() => {
  core = createCarousel({
    count: props.items.length,
    initialIndex: props.initialIndex,
    autoplay: props.autoplay,
    loop: props.loop,
  });
  unsub = core.subscribe((s) => {
    index.value = s.index;
    emit('change', s.index);
  });
  if (props.autoplay > 0) core.startAutoplay();
});

onBeforeUnmount(() => {
  unsub?.();
  core?.destroy();
});
</script>

<template>
  <div class="cc-stage" tabindex="0" @keydown.left="core?.prev({ user: true })"
    @keydown.right="core?.next({ user: true })">
    <div class="cc-carousel">
      <article v-for="(item, i) in items" :key="i" :class="cardCls(i)"
        @click="core?.goTo(i, { user: true })">
        <img class="cc-card__img" :src="item.src" :alt="item.alt || ''" draggable="false" />
        <div class="cc-card__scrim" />
        <header class="cc-card__head">
          <span class="cc-card__num">{{ pad2(i + 1) }}</span>
          <span class="cc-card__num cc-card__num--end">{{ pad2(i + 1) }}</span>
        </header>
        <p class="cc-card__eyebrow">
          <span class="cc-dot" />
          {{ item.eyebrow || 'VISUAL IDENTITY' }}
        </p>
        <h2 class="cc-card__title">{{ item.title }}</h2>
        <div class="cc-card__body">
          <div class="cc-card__info">
            <span class="cc-card__index">{{ pad2(i + 1) }}</span>
            <h3 class="cc-card__heading">{{ item.title }}</h3>
            <p class="cc-card__desc" v-html="(item.desc || '').replace(/\n/g, '<br>')"></p>
            <a v-if="item.href" class="cc-card__cta" :href="item.href" @click.stop>
              View project
              <span class="cc-card__cta-arrow">
                <svg viewBox="0 0 16 16" fill="none">
                  <path d="M3 8h9M8.5 4.5 12 8l-3.5 3.5" stroke="#111" stroke-width="1.5"
                    stroke-linecap="round" stroke-linejoin="round" />
                </svg>
              </span>
            </a>
          </div>
        </div>
      </article>
    </div>

    <footer v-if="showControls" class="cc-controls">
      <div class="cc-controls__counter">
        <span class="cc-counter-current">{{ pad2(index + 1) }}</span>
        <span class="cc-controls__total">/ {{ pad2(items.length) }}</span>
      </div>
      <div class="cc-controls__progress" @click="onProgressClick">
        <div class="cc-controls__bar"
          :style="{ width: 100 / items.length + '%', left: (100 / items.length) * index + '%' }" />
      </div>
      <div class="cc-controls__nav">
        <button class="cc-nav-btn cc-prev" aria-label="上一张"
          :disabled="index === 0 && !loop" @click="core?.prev({ user: true })">
          <svg viewBox="0 0 20 20" fill="none">
            <path d="M11.5 5.5 7 10l4.5 4.5" stroke="currentColor" stroke-width="1.5"
              stroke-linecap="round" stroke-linejoin="round" />
          </svg>
        </button>
        <button class="cc-nav-btn cc-next" aria-label="下一张"
          :disabled="index === items.length - 1 && !loop" @click="core?.next({ user: true })">
          <svg viewBox="0 0 20 20" fill="none">
            <path d="M8.5 5.5 13 10l-4.5 4.5" stroke="currentColor" stroke-width="1.5"
              stroke-linecap="round" stroke-linejoin="round" />
          </svg>
        </button>
      </div>
    </footer>
  </div>
</template>
